/* puts in r0 the string that represent the symbol */

 SYMBOL_STRING:
  PUSH(FP);
  MOV(FP, SP);
  
  CMP(FPARG(1), IMM(1));
  JUMP_LT(HAS_NO_ARGS_SYMBOL_STRING);
  JUMP_GT(TOO_MANY_ARGS_SYMBOL_STRING);
  CMP(IND(FPARG(2)),T_SYMBOL);
  JUMP_NE(NOT_VALID_ARG_SYMBOL_STRING);
  
  MOV (R0,INDD(FPARG(2),1));
  MOV(R0, IND(R0));
  POP(FP);
  RETURN;
  
  NOT_VALID_ARG_SYMBOL_STRING:
  CALL(ERROR_NOT_VALID_ARG);
  
  HAS_NO_ARGS_SYMBOL_STRING:
  CALL(ERROR_NOT_ENOUGH_ARGS);
  
  TOO_MANY_ARGS_SYMBOL_STRING:
  CALL(ERROR_TOO_MANY_ARGS);
